name: flutter_gera_renda
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons and rating star
  cupertino_icons: ^0.1.3
  flutter_svg: 0.17.3+1
  font_awesome_flutter: ^8.8.1
  flutter_rating_bar: ^3.0.1+1

  # internationalization and localization facilities, date/number formatting/parsing
  intl: ^0.16.1

  # dependency injection
  get_it: ^4.0.2

  # introduce functional programming in flutter
  dartz: ^0.9.1
  
  # http client for Flutter
  dio: ^3.0.9

  # open url, phone and others
  url_launcher: ^5.5.0

  shared_preferences: ^0.5.8

  # geolocator
  geolocator: ^5.3.2+2

  # google auth
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4

  # mobx
  mobx:
  flutter_mobx:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/login/
    - assets/service_page/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
